[General]
# background=#0a0a0a  |  background=background.jpg  |  background=/usr/share/backgrounds/default.jpg
# TokyoNight Night #1a1b26 / Storm #24283b / Moon #222436
background=#1a1b26

# date / clock
showDate=true
dateFormat=dddd dd-MM-yyyy
showClock=true
clock12hr=false
clockSeconds=false

# box
hideBorders=false
boxBackground=true
boxBackgroundColor=

# function key
showShutdownKey=true
shutdownKey=F1
showRebootKey=true
rebootKey=F2
showPasswordToggleKey=true
passwordToggleKey=F7

# font
fontFamily=Maple Mono NF CN Medium
fontSize=20
boxFontSize=20

# primaryScreen=false shows login box on all monitors (default)
primaryScreen=false

# session / user / password
defaultInput=password

# input length (box width based on inputLen)
inputLen=30

# password (default null)
asterisk=#
