[General]
# background=#0a0a0a  |  background=background.jpg  |  background=/usr/share/backgrounds/default.jpg
# TokyoNight Night #1a1b26 / Storm #24283b / Moon #222436
background=#1a1b26

# date / clock
showDate=true
dateFormat=dddd dd-MM-yyyy
showClock=true
clock12hr=true
clockSeconds=true

# box
hideBorders=true
boxBackground=true
boxBackgroundColor=#1a1b26

# function key
showShutdownKey=true
shutdownKey=F1
showRebootKey=true
rebootKey=F2
showPasswordToggleKey=true
passwordToggleKey=F7

# font
fontFamily=Maple Mono NF CN Medium
fontSize=15
boxFontSize=15

# session / user / password
defaultInput=user

# input length (box width based on inputLen)
inputLen=20

# password (default null)
asterisk=*
